// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/SvetlovA/agrouter/pkg/runner"
	"sync"
)

// CommandRunnerMock is a mock implementation of main.CommandRunner.
//
//	func TestSomethingThatUsesCommandRunner(t *testing.T) {
//
//		// make and configure a mocked main.CommandRunner
//		mockedCommandRunner := &CommandRunnerMock{
//			RunFunc: func(ctx context.Context, c runner.Command) (int, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedCommandRunner in code that requires main.CommandRunner
//		// and then make assertions.
//
//	}
type CommandRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, c runner.Command) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// C is the c argument value.
			C runner.Command
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *CommandRunnerMock) Run(ctx context.Context, c runner.Command) (int, error) {
	if mock.RunFunc == nil {
		panic("CommandRunnerMock.RunFunc: method is nil but CommandRunner.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
		C   runner.Command
	}{
		Ctx: ctx,
		C:   c,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, c)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedCommandRunner.RunCalls())
func (mock *CommandRunnerMock) RunCalls() []struct {
	Ctx context.Context
	C   runner.Command
} {
	var calls []struct {
		Ctx context.Context
		C   runner.Command
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
