// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/SvetlovA/agrouter/pkg/jev"
	"sync"
)

// JevClientMock is a mock implementation of router.JevClient.
//
//	func TestSomethingThatUsesJevClient(t *testing.T) {
//
//		// make and configure a mocked router.JevClient
//		mockedJevClient := &JevClientMock{
//			AskFunc: func(ctx context.Context, req jev.Request) (map[string]jev.Answer, error) {
//				panic("mock out the Ask method")
//			},
//		}
//
//		// use mockedJevClient in code that requires router.JevClient
//		// and then make assertions.
//
//	}
type JevClientMock struct {
	// AskFunc mocks the Ask method.
	AskFunc func(ctx context.Context, req jev.Request) (map[string]jev.Answer, error)

	// calls tracks calls to the methods.
	calls struct {
		// Ask holds details about calls to the Ask method.
		Ask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req jev.Request
		}
	}
	lockAsk sync.RWMutex
}

// Ask calls AskFunc.
func (mock *JevClientMock) Ask(ctx context.Context, req jev.Request) (map[string]jev.Answer, error) {
	if mock.AskFunc == nil {
		panic("JevClientMock.AskFunc: method is nil but JevClient.Ask was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req jev.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockAsk.Lock()
	mock.calls.Ask = append(mock.calls.Ask, callInfo)
	mock.lockAsk.Unlock()
	return mock.AskFunc(ctx, req)
}

// AskCalls gets all the calls that were made to Ask.
// Check the length with:
//
//	len(mockedJevClient.AskCalls())
func (mock *JevClientMock) AskCalls() []struct {
	Ctx context.Context
	Req jev.Request
} {
	var calls []struct {
		Ctx context.Context
		Req jev.Request
	}
	mock.lockAsk.RLock()
	calls = mock.calls.Ask
	mock.lockAsk.RUnlock()
	return calls
}
